Dutch, Norwegian and Russian
quickgui/quickgui pull request #33
Opened 2021-11-17 04:07 UTC by philclifford

A little knowledge is a dangerous thing, but a little ML and
crowdsourcing can make you feel less nervous.

2021-11-17 04:09 UTC, philclifford commented
Would definitely prefer these not to be merged without native speakers reviewing them.

2021-11-27 13:06 UTC, Sadykhzadeh commented on assets/i18n/ru.po
> +msgstr "Quickgui : Флэттер фронтенд для Quickget и Quickemu"
It would be better to write "Flutter фронтент Quickget и Quickemu"

2021-11-27 13:07 UTC, Sadykhzadeh commented on assets/i18n/ru.po
> +msgstr "Опция поиска"
From my perspective, "Параметры поиска" would be much better.

2021-11-27 13:09 UTC, Sadykhzadeh commented on assets/i18n/ru.po
> +msgstr "Версии"
"Версии" is in plural, I think translating it into "Версия" would be more appropriate option.

2021-11-27 13:11 UTC, Sadykhzadeh requested changes
Overall, the Russian translation is awesome, just some fixes that I commented are recommended to be fixed ^_^

2021-11-27 13:33 UTC, philclifford commented on assets/i18n/ru.po
> +msgstr "Опция поиска"
Thanks.  In the context this string is used as "Search for the option" mainly (but not only) for windows language - hence "option".  Of course I'll take your perspective with many thanks.

2021-11-27 13:43 UTC, philclifford commented
@Sadykhzadeh Thank you so much for your kind words, and for taking the time to improve mine.

2021-12-09 20:37 UTC, merged